# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-22 19:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_month', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
