# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 17:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtmultiscale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prefix')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('basin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Basin')),
                ('alt', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Altitude')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Longitude')),
                ('year_ini', models.IntegerField(blank=True, null=True, verbose_name='Initial Year')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='End Year')),
                ('range', models.IntegerField(blank=True, null=True, verbose_name='Range')),
                ('consistency', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('years', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
