# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtmultiscale', '0002_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
