# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(verbose_name='Code')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainfall.Section')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='code',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='prefix',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Prefix'),
        ),
        migrations.AddField(
            model_name='station',
            name='sub_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rainfall.SubSection'),
            preserve_default=False,
        ),
    ]
