# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0002_auto_20170110_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='average',
            field=models.FloatField(default=1, verbose_name='Average'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='day_amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Day Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='null_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Null Days'),
            preserve_default=False,
        ),
    ]
