# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0003_auto_20170111_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='station',
            name='average',
            field=models.FloatField(blank=True, null=True, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='station',
            name='day_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day Amount'),
        ),
        migrations.AlterField(
            model_name='station',
            name='null_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Null Days'),
        ),
    ]
