# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-08 17:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0005_auto_20170111_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='bbox',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=4),
        ),
        migrations.AddField(
            model_name='subsection',
            name='bbox',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=4),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='station',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Longitude'),
        ),
    ]
