# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0006_auto_20170308_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='alt',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='station',
            name='long',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
