# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0007_auto_20170308_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='average',
            field=models.FloatField(blank=True, null=True, verbose_name='Average'),
        ),
    ]
