# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-11 18:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0008_section_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='null_days_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
