# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-15 17:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0009_station_null_days_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='null_days_array_str',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
