# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0011_station_uni_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Name')),
                ('average', models.FloatField(blank=True, null=True, verbose_name='Average')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainfall.Section')),
            ],
        ),
        migrations.CreateModel(
            name='MonthRain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Name')),
                ('average', models.FloatField(blank=True, null=True, verbose_name='Average')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainfall.Section')),
            ],
        ),
        migrations.CreateModel(
            name='YearRain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Name')),
                ('average', models.FloatField(blank=True, null=True, verbose_name='Average')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainfall.Section')),
            ],
        ),
    ]
