# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0012_dayrain_monthrain_yearrain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayrain',
            name='section',
        ),
        migrations.RemoveField(
            model_name='monthrain',
            name='section',
        ),
        migrations.RemoveField(
            model_name='yearrain',
            name='section',
        ),
        migrations.AddField(
            model_name='dayrain',
            name='station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rainfall.Station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthrain',
            name='station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rainfall.Station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearrain',
            name='station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rainfall.Station'),
            preserve_default=False,
        ),
    ]
